version: '3.1'

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  backend:
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: ["node", "backend.js"]
    ports:
      - "8080:8080"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: fishGameDB
    depends_on:
      - redis
      - mongo

volumes:
  mongodb-data: {}